Feature auth0 decoupling
mumuki/mumukit-auth pull request #14
Opened 2016-12-14 19:51 UTC by flbulgarelli

2016-12-14 20:16 UTC, aguspina requested changes

2016-12-14 20:16 UTC, aguspina commented on lib/mumukit/auth/grant.rb
> +      resource_slug.match_first(@slug.first) && resource_slug.match_second(@slug.second)
`resource_slug.match @slug` is simpler 😛

2016-12-14 20:16 UTC, aguspina commented on lib/mumukit/auth/roles.rb
> +    ROLES = [:student, :teacher, :headmaster, :writer, :editor, :janitor, :owner]
`headmaster` nice choice

2016-12-14 20:16 UTC, aguspina commented on lib/mumukit/auth/slug.rb
> +    alias_method :organization, :first
❤️

2016-12-14 20:16 UTC, aguspina commented on lib/mumukit/auth/token.rb
> +      JWT.encode({aud: Mumukit::Auth.config.client_id, metadata: metadata}, decoded_secret)
why are you encoding metadata?

2016-12-14 20:16 UTC, aguspina commented on lib/mumukit/auth/slug.rb
> +      new(*(parts + ['_'] * 2).take(2))
🤕

2016-12-14 23:35 UTC, flbulgarelli commented on lib/mumukit/auth/grant.rb
> +      resource_slug.match_first(@slug.first) && resource_slug.match_second(@slug.second)
But I need something composable here. The way `AllGrant` and `FirstPartGrant` compare resources is different - it depends on the grant, not the slug.

2016-12-14 23:35 UTC, flbulgarelli commented on lib/mumukit/auth/roles.rb
> +    ROLES = [:student, :teacher, :headmaster, :writer, :editor, :janitor, :owner]
:wink:

2016-12-14 23:37 UTC, flbulgarelli commented on lib/mumukit/auth/token.rb
> +      JWT.encode({aud: Mumukit::Auth.config.client_id, metadata: metadata}, decoded_secret)
Because it must be somewhere. I am reserving the metadata section as a just-in-case dictionary. `mumukit-auth` doesn't rely on its contents.

2016-12-14 23:37 UTC, flbulgarelli commented on lib/mumukit/auth/slug.rb
> +      new(*(parts + ['_'] * 2).take(2))
:disappointed:

2016-12-14 23:56 UTC, flbulgarelli commented on lib/mumukit/auth/slug.rb
> +      new(*(parts + ['_'] * 2).take(2))
Check now @aguspina

2016-12-15 00:19 UTC, aguspina approved these changes

2016-12-15 00:20 UTC, aguspina commented
@fedescarpa please review and merge

2016-12-15 00:20 UTC, aguspina commented
LGTM

2016-12-15 13:31 UTC, merged